export const initialData = [
  {
    id: 1,
    jobRequest: "Launch social media campaign for pro...",
    submitted: "15-11-2024",
    submitterStatus: "Aisha Patel In-process",
    assignedURL: "www.aishapatel.... Sophie Choudhury",
    priority: "Medium",
    dueDate: "20-11-2024",
    estValue: "6,200,000",
  },
  {
    id: 2,
    jobRequest: "Update press kit for company redesign",
    submitted: "28-10-2024",
    submitterStatus: "Irfan Khan Need to start",
    assignedURL: "Tejas Pandey www.irfankhanp...",
    priority: "High",
    dueDate: "30-10-2024",
    estValue: "3,500,000",
  },
  {
    id: 3,
    jobRequest: "Finalize user testing feedback for app...",
    submitted: "05-12-2024",
    submitterStatus: "Mark Johnson In-process",
    assignedURL: "www.markjohns... Rachel Lee",
    priority: "Medium",
    dueDate: "10-12-2024",
    estValue: "4,750,000",
  },
  {
    id: 4,
    jobRequest: "Design new features for the website",
    submitted: "10-01-2025",
    submitterStatus: "Emily Green Complete",
    assignedURL: "Tom Wright www.emilygreen...",
    priority: "Low",
    dueDate: "15-01-2025",
    estValue: "5,900,000",
  },
  {
    id: 5,
    jobRequest: "Prepare financial report for Q4",
    submitted: "25-01-2025",
    submitterStatus: "Blocked Jessica Brown",
    assignedURL: "Kevin Smith www.jessicabro...",
    priority: "Low",
    dueDate: "30-01-2025",
    estValue: "2,800,000",
  },
];
